
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "authentication-04": {
      name: "authentication-04",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/new-york/block/authentication-04")),
      source: "__registry__/new-york/block/authentication-04.tsx",
      files: ["registry/new-york/block/authentication-04.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
  },
}
